# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q77lr3pbw1TxqhjeroG_f7gzQW1ew0YK
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data=pd.read_csv('Renewable_Energy_Adoption.csv')
data.head()

data.isnull().sum()

data.shape

data['adoption'].value_counts()

x=['carbon_emissions']
y=['energy_output']
u=['adoption']

plt.scatter(data['carbon_emissions'], data['energy_output'], c=data['adoption'])
plt.xlabel('carbon_emissions')
plt.ylabel('energy_output')
plt.title('Carbon Emissions vs Energy Output colored by Adoption')
plt.colorbar(label='Adoption')
plt.show()

plt.boxplot([data['carbon_emissions'],data['energy_output']])
plt.show()

sns.pairplot(data, hue='adoption')
plt.show()

x=data[["carbon_emissions",	"energy_output",	"renewability_index",	"cost_efficiency"]]
y=data["adoption"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=DecisionTreeClassifier(max_depth=3,random_state=42)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

accuracy=accuracy_score(y_test,y_pred)
accuracy

conf_matrix=confusion_matrix(y_test,y_pred)
conf_matrix

conf_matrix=confusion_matrix(y_test,y_pred)
sns.heatmap(conf_matrix,annot=True,fmt='d',cmap='Blues',
            xticklabels=['Non-Adoption','Adoption'],
            yticklabels=['Non-Adoption','Adoption'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

print(classification_report(y_test,y_pred,target_names=['Non_Adoption','Adoption']))

import joblib
joblib.dump(model,'Renewable_Energy_Adoption.pkl')

plt.figure(figsize=(12,8))
plot_tree(model,feature_names=x.columns,class_names=['Non-Adoption','Adoption'],filled=True,rounded=True)
plt.savefig('dt1.png')
plt.show()