# -*- coding: utf-8 -*-
"""Iris_Practice_Notebook (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGeMT-a0OGHMzoykE7H2kNNTaQVTGb-u

# Iris Dataset – Practice Notebook

This notebook contains practice questions and starter code for Pandas, NumPy, Matplotlib, Seaborn, and Scikit-learn using the Iris dataset.

## 1. Import Required Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

"""## 2. Load Iris Dataset"""

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df.head()

"""## 3. Pandas Practice"""

# Q1: Display shape and columns
df.shape, df.columns

# Q2: Species count
df['species'].value_counts()

# Q3: Statistical summary
df.describe()

# Q4: Create sepal area
df['sepal_area'] = df['sepal length (cm)'] * df['sepal width (cm)']
df.head()

"""## 4. NumPy Practice"""

X = df.iloc[:, :-2].values

X

# Mean and variance
np.mean(X, axis=0)

np.var(X, axis=0)

# Min-Max normalization
X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_norm

"""## 5. Matplotlib Visualization"""

plt.hist(df['sepal length (cm)'])
plt.title('Sepal Length Distribution')
plt.xlabel('Sepal Length')
plt.ylabel('Frequency')
plt.show()

plt.scatter(df['sepal length (cm)'], df['sepal width (cm)'])
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.show()

"""## 6. Seaborn Visualization"""

sns.pairplot(df, hue='species')
plt.show()

sns.heatmap(df.corr(), annot=True)
plt.show()

"""## 7. Machine Learning – Logistic Regression"""

X = df.iloc[:, :-2]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

import gradio as gr

species_names = iris.target_names

def predict_species(sepal_length, sepal_width, petal_length, petal_width):
    features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    scaled_features = scaler.transform(features)
    prediction = model.predict(scaled_features)[0]
    return species_names[prediction]

iface = gr.Interface(
    fn=predict_species,
    inputs=[
        gr.Number(label='Sepal Length (cm)'),
        gr.Number(label='Sepal Width (cm)'),
        gr.Number(label='Petal Length (cm)'),
        gr.Number(label='Petal Width (cm)')
    ],
    outputs=gr.Text(label='Predicted Species'),
    title='Iris Species Prediction',
    description='Predict the species of Iris flower based on its measurements.'
)

iface.launch()